### ISSUE TITLE
Can you add ConvMAE ?

### ISSUE THREAD

**Issue by gaopengpjlab** [ucasligang/awesome-MIM#6]
ConvMAE: Masked Convolution Meets Masked Autoencoders

https://arxiv.org/abs/2205.03892

https://github.com/alpha-vl/convmae

Please consider the addition of ConvMAE on your repo.

**Comment by ucasligang** [comment]
I have already added ConvMAE, you can check it. If there is any error, feel free to contact me.
Also, Thank your attention to my repo.
